"""Shared defaults for local tool-loop stability controls."""

DEFAULT_DEDUPLICATE_REPEATED_TOOL_RESULTS = True
DEFAULT_TOOL_RESULT_DEDUP_MAX_ENTRIES = 1024
DEFAULT_TOOL_ERROR_REPEAT_GUARD_THRESHOLD = 8

