"""Network error handling utilities for providers."""

import ssl
from typing import Any

import httpx

from astrbot import logger
from astrbot.utils.http_ssl_common import build_ssl_context_with_certifi

_SYSTEM_SSL_CTX = build_ssl_context_with_certifi()

STAINLESS_HEADER_PREFIX = "x-stainless-"


async def strip_sdk_telemetry_headers(request: httpx.Request) -> None:
    """Drop the ``x-stainless-*`` headers a Stainless-generated SDK injected.

    The OpenAI and Anthropic Python SDKs are both generated by Stainless, which
    stamps every request with telemetry headers naming the SDK version, the
    operating system, the CPU architecture and the Python runtime. Some
    OpenAI-compatible relays read those headers as an "official SDK" signature
    and answer with HTTP 403 ``Your request was blocked``, even though the very
    same request sent by curl succeeds. The headers are informational only, so
    dropping them costs nothing and keeps those endpoints reachable.

    Matching on the prefix instead of a fixed list is deliberate: the two SDKs
    already disagree on the exact set (Anthropic also sends
    ``x-stainless-timeout``) and Stainless keeps adding new ones.

    This is wired up as an httpx request event hook rather than as a custom
    transport. httpx resolves proxies through ``mounts``, which take priority
    over an explicitly passed ``transport=``, so a header-stripping transport
    would be silently bypassed for everyone who configured a proxy. Event hooks
    run before transport selection and therefore apply either way.
    """
    for key in [
        key
        for key in request.headers
        if key.lower().startswith(STAINLESS_HEADER_PREFIX)
    ]:
        del request.headers[key]


def resolve_openai_httpx_module() -> Any:
    """Return the ``httpx`` module the OpenAI SDK type-checks ``http_client`` against.

    The SDK validates ``http_client`` with ``isinstance(..., httpx.AsyncClient)``
    against its own ``httpx`` import. When several ``httpx`` installations share
    ``sys.path`` (a bundled Python next to the system one, for example), a client
    built from a different module fails that check, so prefer the SDK's module.
    """
    try:
        from openai import _base_client as openai_base_client
    except ImportError:
        return httpx
    return getattr(openai_base_client, "httpx", httpx)


def resolve_anthropic_httpx_module() -> Any:
    """Return the ``httpx`` module the Anthropic SDK type-checks ``http_client`` against.

    See :func:`resolve_openai_httpx_module` for why this matters.
    """
    try:
        from anthropic import _base_client as anthropic_base_client
    except ImportError:
        return httpx
    return getattr(anthropic_base_client, "httpx", httpx)


def is_connection_error(exc: BaseException) -> bool:
    """Check if an exception is a connection/network related error.

    Uses explicit exception type checking instead of brittle string matching.
    Handles httpx network errors, timeouts, and common Python network exceptions.

    Args:
        exc: The exception to check

    Returns:
        True if the exception is a connection/network error
    """
    # Check for httpx network errors
    if isinstance(
        exc,
        (
            httpx.ConnectError,
            httpx.ConnectTimeout,
            httpx.ReadTimeout,
            httpx.WriteTimeout,
            httpx.PoolTimeout,
            httpx.NetworkError,
            httpx.ProxyError,
            httpx.RequestError,
        ),
    ):
        return True

    # Check for common Python network errors
    if isinstance(exc, (TimeoutError, OSError, ConnectionError)):
        return True

    # Check the __cause__ chain for wrapped connection errors
    cause = getattr(exc, "__cause__", None)
    if cause is not None and cause is not exc:
        return is_connection_error(cause)

    return False


def log_connection_failure(
    provider_label: str,
    error: Exception,
    proxy: str | None = None,
) -> None:
    """Log a connection failure with proxy information.

    If proxy is not provided, will fallback to check os.environ for
    http_proxy/https_proxy environment variables.

    Args:
        provider_label: The provider name for log prefix (e.g., "OpenAI", "Gemini")
        error: The exception that occurred
        proxy: The proxy address if configured, or None/empty string
    """
    import os

    error_type = type(error).__name__

    # Fallback to environment proxy if not configured
    effective_proxy = proxy
    if not effective_proxy:
        effective_proxy = os.environ.get(
            "http_proxy", os.environ.get("https_proxy", "")
        )

    if effective_proxy:
        logger.error(
            f"[{provider_label}] Network or proxy connection failed ({error_type}). "
            f"Proxy: {effective_proxy}; error: {error}"
        )
    else:
        logger.error(
            f"[{provider_label}] Network connection failed ({error_type}): {error}"
        )


def create_proxy_client(
    provider_label: str,
    proxy: str | None = None,
    headers: dict[str, str] | None = None,
    verify: ssl.SSLContext | str | bool | None = None,
    httpx_module: Any = httpx,
) -> httpx.AsyncClient:
    """Create an httpx AsyncClient with proxy configuration if provided.

    Uses a hybrid SSL context that combines the system SSL certificate store
    with certifi as a fallback, ensuring compatibility across different
    environments including Windows where the system store may be incomplete.

    Every request sent through the returned client has its ``x-stainless-*``
    telemetry headers removed; see :func:`strip_sdk_telemetry_headers`.

    Note: The caller is responsible for closing the client when done.
    Consider using the client as a context manager or calling aclose() explicitly.

    Args:
        provider_label: The provider name for log prefix (e.g., "OpenAI", "Gemini")
        proxy: The proxy address (e.g., "http://127.0.0.1:7890"), or None/empty
        headers: Optional custom headers to include in every request
        verify: Optional override for TLS verification. Defaults to the hybrid
                SSL context (system store + certifi) when not provided.
        httpx_module: Optional httpx module to construct AsyncClient from. This is
            useful when a provider SDK performs isinstance checks against its own
            httpx import.

    Returns:
        An httpx.AsyncClient created with the hybrid SSL context (system store + certifi); the proxy is applied only if one is provided.
    """
    resolved_verify = _SYSTEM_SSL_CTX if verify is None else verify
    event_hooks = {"request": [strip_sdk_telemetry_headers]}
    if proxy:
        logger.info(f"[{provider_label}] Using proxy: {proxy}")
        return httpx_module.AsyncClient(
            proxy=proxy,
            verify=resolved_verify,
            headers=headers,
            event_hooks=event_hooks,
        )
    return httpx_module.AsyncClient(
        verify=resolved_verify, headers=headers, event_hooks=event_hooks
    )
