name: "🦄 插件功能需求"
description: 提交新插件功能需求
title: "[PluginWish] 希望有实现 XXXXX 功能的插件"
labels: ["plugin-wish"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交插件功能需求！请详细填写以下信息，以便我们更好地理解您的需求。
        
  - type: textarea
    id: background
    attributes:
      label: "需求背景"
      description: "您为什么需要这个插件？请描述您在使用框架中遇到的问题或痛点"
      placeholder: "例如：目前，llm回复没有表情包，感觉没有拟人味"
    validations:
      required: true

  - type: textarea
    id: coe-features
    attributes:
      label: "核心功能需求"
      description: "请分点描述这个插件应该具备的核心功能。越具体越好。"
      placeholder: |
        * 功能 1: 支持自动识别消息并转发
        * 功能 2: 希望llm可以识别图像
        * 功能 3: 设置定时消息任务
        * ...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: "使用场景和示例"
      description: "请提供一两个具体的使用场景，并展示您期望的输入和输出"
      placeholder: |
        **场景一：**
        - 输入：用户设置了定时任务
        - 期望输出：插件发送了定时消息
        - 使用描述：设置定时任务并发送
        
        **场景二：**
        - 输入：用户发送信息给llm
        - 期望输出：插件帮助llm发送表情包
        - 使用描述：QQ聊天中，支持表情包发送
    validations:
      required: true

  - type: textarea
    id: reference-tools
    attributes:
      label: "参考工具或应用"
      description: "是否有类似功能的其他工具或应用可供参考？请附带链接。"
      placeholder: "例如：astrbot_plugin_turnrig，或者其他框架可以参考的插件。"
    validations:
      required: false

  - type: checkboxes
    id: testing-willingness
    attributes:
      label: "测试意愿"
      description: "您是否愿意参与后续的测试？"
      options:
        - label: "是，我愿意参与测试并提供反馈"
        - label: "否，我只是提出需求"

  - type: textarea
    id: additional-info
    attributes:
      label: "其他补充信息"
      description: "关于这个想法，还有什么需要补充的吗？"
      placeholder: "任何其他相关信息、技术限制、优先级说明等"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "确认"
      description: "请确认您已阅读并同意以下条款"
      options:
        - label: "我已搜索过类似的需求，确认这是一个新的需求"
          required: true
        - label: "我理解这个需求可能需要时间来实现"
          required: true
