# 如果你不知道怎么部署，请务必查看https://soulter.top/posts/qpdg.html

# 不一定需要key了，如果你没有key但有openAI账号或者必应账号，也可以使用下面的逆向库

# 注意：已支持多key自动切换，方法：
# key:
#   - sk-xxxxxx
#   - sk-xxxxxx
# 在下方非注释的地方使用以上格式

# 关于api_base：可以使用一些云函数（如腾讯、阿里）来避免国内被墙的问题。
# 详见：
# https://github.com/Ice-Hazymoon/openai-scf-proxy
# https://github.com/Soulter/QQChannelChatGPT/issues/42
# 设置为none则表示使用官方默认api地址
openai:
  key: 
    - 
  api_base: none
  # 这里是GPT配置，语言模型默认使用gpt-3.5-turbo
  chatGPTConfigs:
    model: gpt-3.5-turbo
    max_tokens: 3000
    temperature: 0.9
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    
  total_tokens_limit: 5000

# QQ开放平台的appid和令牌
# q.qq.com
qqbot:
  appid: 
  token: 

# 设置是否一个人一个会话
uniqueSessionMode: false
# QChannelBot 的版本，请勿修改此字段，否则可能产生一些bug
version: 2.8
# [Beta] 转储历史记录时间间隔(分钟)
dump_history_interval: 10
# 一个用户只能在time秒内发送count条消息
limit:
  time: 60
  count: 5
# 公告
notice: "此机器人由Github项目QQChannelChatGPT驱动。"
# 是否打开私信功能
# 设置为true则频道成员可以私聊机器人。
# 设置为false则频道成员不能私聊机器人。
direct_message_mode: true

# 系统代理
# http_proxy: http://localhost:7890
# https_proxy: http://localhost:7890

# 自定义回复前缀，如[Rev]或其他，务必加引号以防止不必要的bug。
reply_prefix:
  openai_official: "[GPT]"
  rev_chatgpt: "[Rev]"
  rev_edgegpt: "[RevBing]"


################外带程序（插件）################

# 逆向文心一言【暂时不可用，请勿使用】
rev_ernie:
  enable: false

rev_edgegpt:
  enable: false

# 逆向ChatGPT库
# https://github.com/acheong08/ChatGPT
# 优点：免费（无免费额度限制）；
# 缺点：速度相对慢。OpenAI 速率限制：免费帐户每小时 50 个请求。您可以通过多帐户循环来绕过它
# enable设置为true后，将会停止使用上面正常的官方API调用而使用本逆向项目
#
# 多账户可以保证每个请求都能得到及时的回复。
# 关于account的格式
# account:
#   - email: 第1个账户
#     password: 第1个账户密码
#   - email: 第2个账户
#     password: 第2个账户密码
#   - ....
# 支持使用session_token\access_token登录
# 例：
# - session_token: xxxxx
# - access_token: xxxx
# 请严格按照上面这个格式填写。

rev_ChatGPT:
  enable: false
  account:
    - email: 
      password: 
