"""SubAgent DAG Orchestration Engine.

Provides DAG-based task scheduling with topological sort, parallel layer
execution, automatic predecessor result injection, and fail-fast cascade.

Generated by dag_chunk1_impl at 2026-05-26 10:09 CST.
"""

from __future__ import annotations

from collections import deque
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum


class DAGNodeStatus(Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


@dataclass
class DAGTaskNode:
    id: str
    agent_name: str
    prompt: str
    depends_on: list[str] = field(default_factory=list)
    status: DAGNodeStatus = DAGNodeStatus.PENDING
    result: str | None = None
    error: str | None = None
    execution_time: float = 0.0
    subagent_task_id: str | None = None
    started_at: float = 0.0
    completed_at: float = 0.0
    metadata: dict = field(default_factory=dict)


@dataclass
class DAGExecutionContext:
    dag_id: str
    session_id: str
    nodes: dict[str, DAGTaskNode] = field(default_factory=dict)
    adjacency: dict[str, set[str]] = field(default_factory=dict)
    reverse_adjacency: dict[str, set[str]] = field(default_factory=dict)
    topo_layers: list[list[str]] = field(default_factory=list)
    status: str = "PENDING"
    fail_fast: bool = True
    max_parallel: int = 5
    created_at: float = 0.0
    completed_at: float | None = None


class SubAgentDAGEngine:
    """SubAgent DAG orchestration engine."""

    @staticmethod
    def validate_dag(nodes: list[DAGTaskNode]) -> tuple[bool, str | None]:
        """Validate DAG: check dependency existence and detect cycles."""
        valid_ids = {n.id for n in nodes}

        for node in nodes:
            for dep in node.depends_on:
                if dep not in valid_ids:
                    return False, (
                        f"Task '{node.id}' depends on '{dep}' which is not defined. "
                        f"Available: {sorted(valid_ids)}"
                    )

        try:
            SubAgentDAGEngine._kahn_sort(nodes)
        except ValueError as e:
            return False, str(e)

        return True, None

    @staticmethod
    def _kahn_sort(nodes: list[DAGTaskNode]) -> list[list[str]]:
        """Kahn's topological sort returning layers for parallel execution.

        Raises ValueError on cycle detection.
        """
        if not nodes:
            return []

        in_degree: dict[str, int] = {n.id: 0 for n in nodes}
        successors: dict[str, set[str]] = {n.id: set() for n in nodes}

        for node in nodes:
            for dep in node.depends_on:
                successors[dep].add(node.id)
                in_degree[node.id] += 1

        queue = deque([nid for nid, deg in in_degree.items() if deg == 0])
        layers: list[list[str]] = []
        sorted_count = 0

        while queue:
            current_layer: list[str] = []
            for _ in range(len(queue)):
                node_id = queue.popleft()
                current_layer.append(node_id)
                sorted_count += 1
                for succ in successors[node_id]:
                    in_degree[succ] -= 1
                    if in_degree[succ] == 0:
                        queue.append(succ)
            layers.append(current_layer)

        if sorted_count != len(nodes):
            cycle_nodes = [nid for nid, deg in in_degree.items() if deg > 0]
            cycle_desc = " -> ".join(cycle_nodes[:5])
            if len(cycle_nodes) > 5:
                cycle_desc += " -> ..."
            raise ValueError(f"Cycle detected: {cycle_desc}")

        return layers

    @staticmethod
    def _get_ready_nodes(ctx: DAGExecutionContext) -> list[str]:
        """Find all PENDING nodes whose predecessors are all COMPLETED."""
        ready: list[str] = []
        for node_id, node in ctx.nodes.items():
            if node.status != DAGNodeStatus.PENDING:
                continue
            predecessors = ctx.reverse_adjacency.get(node_id, set())
            if all(
                ctx.nodes[p].status == DAGNodeStatus.COMPLETED for p in predecessors
            ):
                ready.append(node_id)
        return ready

    @staticmethod
    def _cascade_skip(ctx: DAGExecutionContext, failed_node_id: str) -> list[str]:
        """BFS: mark all transitive successors of a failed node as SKIPPED."""
        skipped: list[str] = []
        queue: deque[str] = deque([failed_node_id])
        while queue:
            current = queue.popleft()
            for successor in ctx.adjacency.get(current, set()):
                node = ctx.nodes[successor]
                if node.status == DAGNodeStatus.PENDING:
                    node.status = DAGNodeStatus.SKIPPED
                    skipped.append(successor)
                    queue.append(successor)
        return skipped

    @staticmethod
    def _build_injected_context(
        node: DAGTaskNode,
        ctx: DAGExecutionContext,
        max_inject_length: int = 4000,
    ) -> list[dict]:
        """Build context messages containing predecessor results."""
        predecessor_ids = ctx.reverse_adjacency.get(node.id, set())
        if not predecessor_ids:
            return []

        NL = "\n"
        parts: list[str] = []
        parts.append(
            "[DAG Context] The following tasks your work depends on have completed:"
            + NL
        )

        for pred_id in sorted(predecessor_ids):
            pred = ctx.nodes[pred_id]
            result_text = pred.result or "(empty result)"
            if len(result_text) > max_inject_length:
                omitted = len(result_text) - max_inject_length
                result_text = (
                    result_text[:max_inject_length]
                    + NL
                    + f"...[truncated, {omitted} chars omitted]"
                )
            parts.append(
                f"## Result of '{pred_id}' (completed in {pred.execution_time:.1f}s)"
                + NL
                + result_text
                + NL
            )

        parts.append("---" + NL + "Now proceed with your task.")
        return [{"role": "user", "content": NL.join(parts)}]

    @staticmethod
    async def _execute_single_node(
        ctx: DAGExecutionContext,
        node_id: str,
        session_id: str,
        max_inject_length: int = 4000,
        launch_fn: Callable | None = None,
    ) -> None:
        """Execute a single DAG node.

        If *launch_fn* is provided, it is called with (node, session_id,
        injected_context) and should launch the subagent then store the result
        into SubAgentManager.subagent_background_results.  The method then polls
        for the stored result.

        If *launch_fn* is None, the method polls assuming someone else
        launched the subagent (e.g. via an external background task).
        """
        import asyncio
        import time as time_mod

        from astrbot.core.subagent_manager import SubAgentManager

        node = ctx.nodes[node_id]
        node.status = DAGNodeStatus.RUNNING
        node.started_at = time_mod.time()

        # Create pending task for lifecycle tracking and
        # task_id-based result matching (not timestamp heuristics).
        task_id = SubAgentManager.create_pending_subagent_task(
            session_id, node.agent_name
        )
        node.subagent_task_id = task_id

        try:
            injected_context = SubAgentDAGEngine._build_injected_context(
                node, ctx, max_inject_length=max_inject_length
            )

            if launch_fn is not None:
                asyncio.create_task(
                    launch_fn(node, session_id, injected_context, task_id)
                )

            start = time_mod.time()
            while True:
                result = SubAgentManager.get_subagent_result(
                    session_id, node.agent_name, task_id=task_id
                )
                if result and (result.result or result.completed_at > 0):
                    node.execution_time = time_mod.time() - start
                    node.completed_at = time_mod.time()
                    if result.success:
                        node.status = DAGNodeStatus.COMPLETED
                        node.result = result.result or ""
                    else:
                        node.status = DAGNodeStatus.FAILED
                        node.error = result.error or "Unknown error"
                    return

                session = SubAgentManager.get_session(session_id)
                if not session:
                    node.status = DAGNodeStatus.FAILED
                    node.error = "Session lost during execution"
                    return

                timeout = SubAgentManager.get_execution_timeout()
                if timeout > 0 and (time_mod.time() - start) > timeout:
                    node.status = DAGNodeStatus.FAILED
                    node.error = f"Timeout after {timeout:.1f}s"
                    return

                await asyncio.sleep(0.5)

        except Exception as e:
            node.status = DAGNodeStatus.FAILED
            node.error = str(e)
            node.execution_time = time_mod.time() - node.started_at
            node.completed_at = time_mod.time()

    @staticmethod
    async def execute_dag(
        ctx: DAGExecutionContext,
        session_id: str,
        max_inject_length: int = 4000,
        launch_fn: Callable | None = None,
    ) -> dict:
        """Execute the entire DAG synchronously.

        Args:
            launch_fn: Optional async callable(node, session_id, injected_context)
                that launches the subagent. If None, polling-only mode is used.

        Returns:
            dict with keys: "failed", "skipped", "succeeded", "formatted", "total_time".
        """
        import asyncio
        import time as time_mod

        from astrbot import logger as _dag_logger

        ctx.status = "RUNNING"
        dag_start = time_mod.time()

        try:
            for layer in ctx.topo_layers:
                # Process layer in waves. Each wave runs at most one task
                # per agent to prevent context pollution from concurrent
                # tasks on the same subagent.
                while True:
                    batch: list[str] = []
                    used_agents: set[str] = set()
                    for nid in layer:
                        if len(batch) >= ctx.max_parallel:
                            break
                        node = ctx.nodes[nid]
                        if node.status != DAGNodeStatus.PENDING:
                            continue
                        if node.agent_name not in used_agents:
                            batch.append(nid)
                            used_agents.add(node.agent_name)

                    if not batch:
                        break  # No more PENDING nodes in this layer

                    for nid in batch:
                        ctx.nodes[nid].status = DAGNodeStatus.READY

                    tasks = []
                    for nid in batch:
                        node = ctx.nodes[nid]
                        if node.status in (
                            DAGNodeStatus.SKIPPED,
                            DAGNodeStatus.FAILED,
                        ):
                            continue
                        tasks.append(
                            SubAgentDAGEngine._execute_single_node(
                                ctx,
                                nid,
                                session_id,
                                max_inject_length,
                                launch_fn=launch_fn,
                            )
                        )

                    if tasks:
                        await asyncio.gather(*tasks, return_exceptions=True)

                    for nid in batch:
                        node = ctx.nodes[nid]
                        if node.status == DAGNodeStatus.FAILED and ctx.fail_fast:
                            _dag_logger.warning(
                                f"[SubAgent:DAG] Node '{nid}' failed, cascading skip"
                            )
                            SubAgentDAGEngine._cascade_skip(ctx, nid)
                            # Stop processing this layer
                            batch = []
                            break

                    if not batch:
                        break  # fail-fast terminated layer

        finally:
            ctx.completed_at = time_mod.time()

        succeeded = sum(
            1 for n in ctx.nodes.values() if n.status == DAGNodeStatus.COMPLETED
        )
        failed = sum(1 for n in ctx.nodes.values() if n.status == DAGNodeStatus.FAILED)
        skipped = sum(
            1 for n in ctx.nodes.values() if n.status == DAGNodeStatus.SKIPPED
        )
        total_time = ctx.completed_at - dag_start

        formatted = _format_dag_result(ctx, succeeded, failed, skipped, total_time)

        return {
            "failed": failed,
            "skipped": skipped,
            "succeeded": succeeded,
            "formatted": formatted,
            "total_time": total_time,
        }


def _format_dag_result(
    ctx: DAGExecutionContext,
    succeeded: int,
    failed: int,
    skipped: int,
    total_time: float,
) -> str:
    """Format the aggregated DAG execution result for LLM consumption."""
    lines: list[str] = []

    if failed == 0 and skipped == 0:
        lines.append(
            "✅ DAG orchestration completed: "
            + f"{succeeded}/{len(ctx.nodes)} tasks succeeded in {total_time:.1f}s"
        )
    else:
        lines.append(
            "❌ DAG orchestration failed: "
            + f"{succeeded}/{len(ctx.nodes)} succeeded"
            + (f", {failed} failed" if failed else "")
            + (f", {skipped} skipped" if skipped else "")
            + f" in {total_time:.1f}s"
        )

    for layer in ctx.topo_layers:
        parallel_str = f" ({len(layer)} parallel)" if len(layer) > 1 else ""
        lines.append(f"Layer{parallel_str}:")
        for nid in layer:
            node = ctx.nodes[nid]
            if node.status == DAGNodeStatus.COMPLETED:
                lines.append(
                    f"  ✓ {nid} ({node.agent_name}) — {node.execution_time:.1f}s"
                )
                if node.result:
                    preview = node.result[:300]
                    if len(node.result) > 300:
                        preview += "..."
                    lines.append(f"     {preview}")
            elif node.status == DAGNodeStatus.FAILED:
                lines.append(
                    f"  ✗ {nid} ({node.agent_name}) — FAILED after "
                    f"{node.execution_time:.1f}s"
                )
                if node.error:
                    lines.append(f"     Error: {node.error}")
            elif node.status == DAGNodeStatus.SKIPPED:
                lines.append(
                    f"  ⊘ {nid} ({node.agent_name}) — skipped (dependency failed)"
                )
        lines.append("")

    if failed > 0 or skipped > 0:
        lines.append(
            f"Summary: {succeeded} succeeded, {failed} failed, "
            f"{skipped} skipped. Total time: {total_time:.1f}s"
        )

    newline = chr(10)
    return newline.join(lines)
