"""Tests for SubAgent DAG Orchestration Engine.

Generated by dag_chunk1_impl at 2026-05-26 10:09 CST.
"""

from astrbot.core.subagent_dag import (
    DAGNodeStatus,
    DAGTaskNode,
    DAGExecutionContext,
    SubAgentDAGEngine,
)


def test_dag_task_node_defaults():
    node = DAGTaskNode(id="step1", agent_name="researcher", prompt="Do research")
    assert node.id == "step1"
    assert node.agent_name == "researcher"
    assert node.prompt == "Do research"
    assert node.depends_on == []
    assert node.status == DAGNodeStatus.PENDING
    assert node.result is None
    assert node.error is None


def test_dag_task_node_with_dependencies():
    node = DAGTaskNode(
        id="step2", agent_name="writer", prompt="Write report", depends_on=["step1"]
    )
    assert node.depends_on == ["step1"]
    assert node.status == DAGNodeStatus.PENDING


# ============================================================
# TASK 1.2: Kahn topological sort with cycle detection
# ============================================================


def test_topological_sort_linear_chain():
    """A -> B -> C"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="Task A"),
        DAGTaskNode(id="B", agent_name="b", prompt="Task B", depends_on=["A"]),
        DAGTaskNode(id="C", agent_name="c", prompt="Task C", depends_on=["B"]),
    ]
    layers = SubAgentDAGEngine._kahn_sort(nodes)
    assert layers == [["A"], ["B"], ["C"]]


def test_topological_sort_parallel_diamond():
    """A and B are independent, C depends on both, D depends on C"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="Task A"),
        DAGTaskNode(id="B", agent_name="b", prompt="Task B"),
        DAGTaskNode(id="C", agent_name="c", prompt="Task C", depends_on=["A", "B"]),
        DAGTaskNode(id="D", agent_name="d", prompt="Task D", depends_on=["C"]),
    ]
    layers = SubAgentDAGEngine._kahn_sort(nodes)
    assert layers[0] == ["A", "B"] or layers[0] == ["B", "A"]
    assert layers[1] == ["C"]
    assert layers[2] == ["D"]


def test_topological_sort_mixed():
    """A, B independent; C depends on A; D depends on B and C"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="A"),
        DAGTaskNode(id="B", agent_name="b", prompt="B"),
        DAGTaskNode(id="C", agent_name="c", prompt="C", depends_on=["A"]),
        DAGTaskNode(id="D", agent_name="d", prompt="D", depends_on=["B", "C"]),
    ]
    layers = SubAgentDAGEngine._kahn_sort(nodes)
    assert set(layers[0]) == {"A", "B"}
    assert layers[1] == ["C"]
    assert layers[2] == ["D"]


def test_cycle_detection_simple():
    """A -> B -> A"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="A", depends_on=["B"]),
        DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"]),
    ]
    valid, error = SubAgentDAGEngine.validate_dag(nodes)
    assert valid is False
    assert "Cycle" in error


def test_cycle_detection_indirect():
    """A -> B -> C -> A"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="A", depends_on=["C"]),
        DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"]),
        DAGTaskNode(id="C", agent_name="c", prompt="C", depends_on=["B"]),
    ]
    valid, error = SubAgentDAGEngine.validate_dag(nodes)
    assert valid is False
    assert "Cycle" in error


def test_missing_dependency_reference():
    """B depends on X which doesn't exist"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="A"),
        DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["X"]),
    ]
    valid, error = SubAgentDAGEngine.validate_dag(nodes)
    assert valid is False
    assert "X" in error


def test_no_dependency_all_parallel():
    """All nodes independent"""
    nodes = [
        DAGTaskNode(id="A", agent_name="a", prompt="A"),
        DAGTaskNode(id="B", agent_name="b", prompt="B"),
        DAGTaskNode(id="C", agent_name="c", prompt="C"),
    ]
    layers = SubAgentDAGEngine._kahn_sort(nodes)
    assert len(layers) == 1
    assert set(layers[0]) == {"A", "B", "C"}


def test_single_node():
    nodes = [DAGTaskNode(id="A", agent_name="a", prompt="A")]
    layers = SubAgentDAGEngine._kahn_sort(nodes)
    assert layers == [["A"]]


# ============================================================
# TASK 1.3: Ready node detection and cascade skip
# ============================================================

import time


def _make_ctx(nodes: list[DAGTaskNode]) -> DAGExecutionContext:
    """Helper to build a DAGExecutionContext from nodes."""
    node_map = {n.id: n for n in nodes}
    adj: dict[str, set[str]] = {n.id: set() for n in nodes}
    rev_adj: dict[str, set[str]] = {n.id: set() for n in nodes}
    for n in nodes:
        for dep in n.depends_on:
            adj[dep].add(n.id)
            rev_adj[n.id].add(dep)
    return DAGExecutionContext(
        dag_id="test-dag-1",
        session_id="test-session",
        nodes=node_map,
        adjacency=adj,
        reverse_adjacency=rev_adj,
        created_at=time.time(),
    )


def test_get_ready_nodes_all_pending_with_done_predecessors():
    a = DAGTaskNode(id="A", agent_name="a", prompt="A", status=DAGNodeStatus.COMPLETED)
    b = DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"])
    c = DAGTaskNode(id="C", agent_name="c", prompt="C")
    ctx = _make_ctx([a, b, c])
    ready = SubAgentDAGEngine._get_ready_nodes(ctx)
    assert set(ready) == {"B", "C"}


def test_get_ready_nodes_blocked_by_pending_predecessor():
    """A is RUNNING (was already dispatched) → B should NOT be ready."""
    a = DAGTaskNode(id="A", agent_name="a", prompt="A", status=DAGNodeStatus.RUNNING)
    b = DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"])
    ctx = _make_ctx([a, b])
    ready = SubAgentDAGEngine._get_ready_nodes(ctx)
    assert ready == []


def test_get_ready_nodes_blocked_by_running_predecessor():
    a = DAGTaskNode(id="A", agent_name="a", prompt="A", status=DAGNodeStatus.RUNNING)
    b = DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"])
    ctx = _make_ctx([a, b])
    ready = SubAgentDAGEngine._get_ready_nodes(ctx)
    assert ready == []


def test_get_ready_nodes_already_running_node_not_returned():
    a = DAGTaskNode(id="A", agent_name="a", prompt="A", status=DAGNodeStatus.COMPLETED)
    b = DAGTaskNode(
        id="B", agent_name="b", prompt="B", depends_on=["A"], status=DAGNodeStatus.READY
    )
    ctx = _make_ctx([a, b])
    ready = SubAgentDAGEngine._get_ready_nodes(ctx)
    assert ready == []


def test_cascade_skip_simple():
    a = DAGTaskNode(id="A", agent_name="a", prompt="A", status=DAGNodeStatus.FAILED)
    b = DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"])
    c = DAGTaskNode(id="C", agent_name="c", prompt="C")
    ctx = _make_ctx([a, b, c])
    skipped = SubAgentDAGEngine._cascade_skip(ctx, "A")
    assert "B" in skipped
    assert ctx.nodes["B"].status == DAGNodeStatus.SKIPPED
    assert ctx.nodes["C"].status == DAGNodeStatus.PENDING


def test_cascade_skip_transitive():
    a = DAGTaskNode(id="A", agent_name="a", prompt="A", status=DAGNodeStatus.FAILED)
    b = DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"])
    c = DAGTaskNode(id="C", agent_name="c", prompt="C", depends_on=["B"])
    ctx = _make_ctx([a, b, c])
    skipped = SubAgentDAGEngine._cascade_skip(ctx, "A")
    assert set(skipped) == {"B", "C"}
    assert ctx.nodes["B"].status == DAGNodeStatus.SKIPPED
    assert ctx.nodes["C"].status == DAGNodeStatus.SKIPPED


# ============================================================
# TASK 1.4: Predecessor result injection
# ============================================================


def test_build_injected_context_single_predecessor():
    ctx = _make_ctx(
        [
            DAGTaskNode(
                id="A",
                agent_name="a",
                prompt="A",
                status=DAGNodeStatus.COMPLETED,
                result="Research findings here",
                execution_time=12.3,
            ),
            DAGTaskNode(
                id="B", agent_name="b", prompt="Write report", depends_on=["A"]
            ),
        ]
    )
    node_b = ctx.nodes["B"]
    messages = SubAgentDAGEngine._build_injected_context(node_b, ctx)
    assert len(messages) == 1
    content = messages[0]["content"]
    assert "[DAG Context]" in content
    assert "Result of 'A'" in content
    assert "Research findings here" in content
    assert "completed in 12.3s" in content


def test_build_injected_context_multiple_predecessors():
    ctx = _make_ctx(
        [
            DAGTaskNode(
                id="A",
                agent_name="a",
                prompt="A",
                status=DAGNodeStatus.COMPLETED,
                result="Data result",
                execution_time=5.0,
            ),
            DAGTaskNode(
                id="B",
                agent_name="b",
                prompt="B",
                status=DAGNodeStatus.COMPLETED,
                result="Analysis result",
                execution_time=8.0,
            ),
            DAGTaskNode(
                id="C", agent_name="c", prompt="Synthesize", depends_on=["A", "B"]
            ),
        ]
    )
    node_c = ctx.nodes["C"]
    messages = SubAgentDAGEngine._build_injected_context(node_c, ctx)
    content = messages[0]["content"]
    assert "Result of 'A'" in content
    assert "Result of 'B'" in content
    assert "Data result" in content
    assert "Analysis result" in content


def test_build_injected_context_no_predecessors():
    ctx = _make_ctx([DAGTaskNode(id="A", agent_name="a", prompt="A")])
    node_a = ctx.nodes["A"]
    messages = SubAgentDAGEngine._build_injected_context(node_a, ctx)
    assert messages == []


def test_build_injected_context_truncation():
    long_result = "X" * 5000
    ctx = _make_ctx(
        [
            DAGTaskNode(
                id="A",
                agent_name="a",
                prompt="A",
                status=DAGNodeStatus.COMPLETED,
                result=long_result,
                execution_time=1.0,
            ),
            DAGTaskNode(id="B", agent_name="b", prompt="B", depends_on=["A"]),
        ]
    )
    node_b = ctx.nodes["B"]
    messages = SubAgentDAGEngine._build_injected_context(
        node_b, ctx, max_inject_length=4000
    )
    content = messages[0]["content"]
    assert "truncated" in content.lower()
    assert len(content) < 4500
